//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdcDl
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AIS_DEV : DbContext
    {
        public AIS_DEV()
            : base("name=AIS_DEV")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VDC_ELEVATIONS> VDC_ELEVATIONS { get; set; }
        public virtual DbSet<VDC_FILE_MAPPINGS> VDC_FILE_MAPPINGS { get; set; }
        public virtual DbSet<VDC_FILES> VDC_FILES { get; set; }
        public virtual DbSet<VDC_PROJECTS> VDC_PROJECTS { get; set; }
        public virtual DbSet<VDC_TRADE_INFO> VDC_TRADE_INFO { get; set; }
    }
}
