//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdcDl
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDC_PROJECTS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VDC_PROJECTS()
        {
            this.VDC_ELEVATIONS = new HashSet<VDC_ELEVATIONS>();
            this.VDC_FILE_MAPPINGS = new HashSet<VDC_FILE_MAPPINGS>();
            this.VDC_FILES = new HashSet<VDC_FILES>();
            this.VDC_TRADE_INFO = new HashSet<VDC_TRADE_INFO>();
        }
    
        public decimal VDC_PROJECT_ID { get; set; }
        public decimal ROW_VERSION { get; set; }
        public decimal PROJECT_NUMBER { get; set; }
        public string PROJECT_NAME { get; set; }
        public string JOB_NAME_MULTILINE { get; set; }
        public string ADDRESS { get; set; }
        public string INTERNAL_EMAIL_GROUP { get; set; }
        public string EXTERNAL_EMAIL_GROUP { get; set; }
        public string GC { get; set; }
        public string PRIMARY_FTP { get; set; }
        public string SECONDARY_FTP { get; set; }
        public System.DateTime CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VDC_ELEVATIONS> VDC_ELEVATIONS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VDC_FILE_MAPPINGS> VDC_FILE_MAPPINGS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VDC_FILES> VDC_FILES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VDC_TRADE_INFO> VDC_TRADE_INFO { get; set; }
    }
}
