//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdcDl
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDC_FILE_MAPPINGS
    {
        public decimal VDC_FILE_MAPPING_ID { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public decimal ROW_VERSION { get; set; }
        public decimal MAP_PROJECT_NUMBER { get; set; }
        public string MAP_FTP_SOURCE { get; set; }
        public string MAP_COMPANY_ID { get; set; }
        public string MAP_PROJECT_ID { get; set; }
        public string MAP_TYPE { get; set; }
        public string MAPPING_ID { get; set; }
        public System.DateTime CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual VDC_PROJECTS VDC_PROJECTS { get; set; }
    }
}
