//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdcDl
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDC_ELEVATIONS
    {
        public decimal VDC_ELEVATION_ID { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public decimal ROW_VERSION { get; set; }
        public decimal ELEV_PROJECT_NUMBER { get; set; }
        public string ELEV_LEVEL { get; set; }
        public string ELEV_ELEVATION { get; set; }
        public string ELEV_REVIT_ELEVATION { get; set; }
        public string ELEV_LEVEL_ABOVE { get; set; }
        public System.DateTime CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string ELEV_LEVEL_BELOW { get; set; }
        public string ELEV_JCC_GRID { get; set; }
        public string ELEV_VDC_MASTER { get; set; }
    
        public virtual VDC_PROJECTS VDC_PROJECTS { get; set; }
    }
}
