//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdcDl
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDC_FILES
    {
        public decimal VDC_FILE_ID { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public decimal ROW_VERSION { get; set; }
        public decimal FILE_PROJECT_NUMBER { get; set; }
        public string FILE_LEVEL { get; set; }
        public string FILE_TRADE_ABBREVIATION { get; set; }
        public string FILE_INTERNAL_NAME { get; set; }
        public string FILE_EXTERNAL_NAME { get; set; }
        public string FILE_EXTENSION { get; set; }
        public Nullable<decimal> FILE_IS_PARENT { get; set; }
        public string FILE_ACTION { get; set; }
        public string FILE_PARENT_NAME { get; set; }
        public string FILE_SCRIPTS { get; set; }
        public Nullable<System.DateTime> FILE_LAST_PROCESSED { get; set; }
        public System.DateTime CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
        public string FILE_STATUS { get; set; }
        public string FILE_NOTE { get; set; }
        public Nullable<decimal> FILE_VERSION { get; set; }
    
        public virtual VDC_PROJECTS VDC_PROJECTS { get; set; }
    }
}
