//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VdcDl
{
    using System;
    using System.Collections.Generic;
    
    public partial class VDC_TRADE_INFO
    {
        public decimal VDC_TRADE_INFO_ID { get; set; }
        public Nullable<decimal> PROJECT_ID { get; set; }
        public decimal ROW_VERSION { get; set; }
        public decimal TI_PROJECT_NUMBER { get; set; }
        public string TI_TRADE_ABBREVIATION { get; set; }
        public Nullable<decimal> TI_OWNED { get; set; }
        public string TI_TRADE_NAME { get; set; }
        public string TI_SUBDIRECTORY { get; set; }
        public string TI_COLOR { get; set; }
        public Nullable<decimal> TI_XTC { get; set; }
        public string TI_ELEVATION_TO_USE { get; set; }
        public System.DateTime CREATED { get; set; }
        public string CREATED_BY { get; set; }
        public System.DateTime UPDATED { get; set; }
        public string UPDATED_BY { get; set; }
    
        public virtual VDC_PROJECTS VDC_PROJECTS { get; set; }
    }
}
